include:
  - cider-ci/task-components/bundle.yml

traits:
  asdf: true
  PostgreSQL 15: true

scripts:

  datalayer-configure-rails-db:
    # NOTE: also sets up 'production', needed for asset precompilation
    start_when:
      ruby has been bundled:
        script_key: datalayer-bundle-ruby
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $DATALAYER_DIR
      source $DATALAYER_DIR/cider-ci/bin/pg_env_set
      ./cider-ci/bin/configure-rails-db

  create-database:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      source $DATALAYER_DIR/cider-ci/bin/pg_env_set
      createdb "$DATABASE"
      psql -d "$DATABASE" -f ${DATALAYER_DIR}/db/structure.sql

  test:
    start_when:
      database has been created:
        script_key: create-database
      database has been configured:
        script_key: datalayer-configure-rails-db

  delete-database:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      source $DATALAYER_DIR/cider-ci/bin/pg_env_set
      dropdb --if-exists -f "$DATABASE"
    start_when:
      test is in termial state:
        script_key: test
        states: [aborted, passed, failed, skipped]
