jobs:
  all-tests:
    name: All Tests
    descriptions: |
      This job depends on all other tests and checks
      and it will pass if and only if all dependencies have passed.
    depends-on:
    - type: job
      job: tests
      states: [passed]
    - type: job
      job: code-checks
      states: [passed]
    run-on:
    - type: branch
      include-match: ^.+$
    context:
      tasks:
        all:
          scripts:
            body: echo 'Yay, all dependencies have passed!'

_cider-ci_include:
  - cider-ci/jobs/code-checks.yml
  - cider-ci/jobs/tests.yml
