jobs:

  all-tests:
    name: All Tests
    description: |
      This job depends on all unit jobs that need to pass.
      It is depended upon by the super-project(s)!
    priority: 999 # "empty" job = high priority
    depends_on:
      rspec-tests: { job_key: rspec-tests, states: [passed], type: job }
      lint: { job_key: lint, states: [passed], type: job }
    run_when:
      'rspec-tests passed':
        type: job
        job_key: rspec-tests
        states: [passed]
      'lint passed':
        type: job
        job_key: lint
        states: [passed]
      'meta passed':
        type: job
        job_key: meta
        states: [passed]
    context:
      task: "echo '✔︎ All dependencies have passed' ; exit 0"

  rspec-tests:
    name: RSpec Tests
    description: Run all specs.
    priority: 1
    run_when: &DEFAULT_TRIGGERS
      any branch matches:
        type: branch
        include_match: ^.+$
    context:
      include: cider-ci/context-components/rspec.yml

  meta: 
    name: DB Meta Checks
    run_when: *DEFAULT_TRIGGERS
    priority: 2
    context:
      include: cider-ci/context-components/meta.yml

  lint:
    name: "Linting"
    description: |
      Code checks: static checks and metrics: complexity, duplication, and format,
      also other consistency checks.
    priority: 2
    run_when: *DEFAULT_TRIGGERS
    context:
      task_defaults:
        environment_variables:
          GIT_LINEAR_HISTORY_CHECK_START_SHA: ec23e77651c3b80d4343ead339514512aff946c1
          DATALAYER_DIR: '{{CIDER_CI_WORKING_DIR}}'
      contexts:
        include:
          - path: cider-ci/context-components/lint/git-lint.yml
          - path: cider-ci/context-components/lint/rspec-lint.yml

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# GITHUB BRANCH PROTECTION                                                        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  good-to-merge:
    name: "⚑ Good To Merge"
    description: |
      This job depends on all jobs that need to pass for "Delivery".
      It is depended upon by GitHub's branch protection (for `master`)!
    priority: 999 # "delivery" job = high priority
    context:
      task: "echo '✔︎ All dependencies have passed and there are no submodules to check' ; exit 0"
    # NOTE: no submodules, so we *want* to auto-trigger this!
    # Having this job is just for consistency (also easier to add a submodule later)
    depends_on: &ALL_PASSED
      'all tests passed': {type: job, job_key: 'all-tests', states: [passed]}
    run_when: *ALL_PASSED
