jobs:

  all-tests:
    name: All Tests
    description: |
      This job depends on all other tests and checks
      and it will pass if and only if all dependencies have passed.
    priority: 999 # "empty" job = high priority
    depends_on:
      rspec tests:
        type: job
        job_key: rspec-tests
        states: [passed]
      code checks:
        type: job
        job_key: code-checks
        states: [passed]
    run_when:
      any branch matches:
        type: branch
        include_match: ^.+$
    context:
      task: |
        echo 'Yay, all dependencies have passed!'
        exit 0

  code-checks:
    name: Code-Checks
    description: |
      Run static checks and metrics: complexity, duplication, and code format.
    priority: 1
    run_when:
      'any branch matches':
        type: branch
        include_match: ^.+$
    context:
      include: cider-ci_v4/contexts/code-checks.yml

  rspec-tests:
    name: RSpec Tests
    description: Run all specs.
    priority: 1
    run_when:
      any branch matches:
        type: branch
        include_match: ^.+$
    context:
      include: cider-ci_v4/contexts/rspec.yml
