jobs:

  all-tests:
    name: All Tests
    description: |
      This job depends on all other tests and checks
      and it will pass if and only if all dependencies have passed.
    priority: 999 # "empty" job = high priority
    depends_on:
      rspec tests:
        type: job
        job_key: rspec-tests
        states: [passed]
      code checks:
        type: job
        job_key: code-checks
        states: [passed]
    run_when: &DEFAULT_TRIGGERS
      any branch matches:
        type: branch
        include_match: ^.+$
    context:
      task: |
        echo 'Yay, all dependencies have passed!'
        exit 0

  code-checks:
    name: Code-Checks
    description: |
      Run static checks and metrics: complexity, duplication, and code format.
    priority: 1
    run_when: *DEFAULT_TRIGGERS
    context:
      include: cider-ci/contexts/code-checks.yml

  rspec-tests:
    name: RSpec Tests
    description: Run all specs.
    priority: 1
    run_when: *DEFAULT_TRIGGERS
    context:
      include: cider-ci/contexts/rspec.yml

  meta-checks:
    name: Meta
    description: |
      Tasks that rely on external (out-of-repository) state.
      Their state is not as fixed as in the other Jobs, so it might change over time.
    priority: 3 # "I don't always run this, but when I do, it should be fast"
    run_when: *DEFAULT_TRIGGERS
    context:
      include: cider-ci/contexts/meta-checks.yml
      task_defaults:
        environment_variables:
          GIT_LINEAR_HISTORY_CHECK_START_SHA: ec23e77651c3b80d4343ead339514512aff946c1

  good-to-merge:
    name: "Good To Merge"
    description: |
      This job depends on all jobs that need to pass for "Delivery".
      It is depended upon by GitHub's branch protection (for `master`)!
    priority: 999 # "empty" job = high priority
    context:
      task: "echo '✔︎ All dependencies have passed' ; exit 0"
    run_when: *DEFAULT_TRIGGERS
    depends_on:
      all-tests: {job_key: all-tests, type: job, states: [passed]}
      meta-checks: {job_key: meta-checks, type: job, states: [passed]}

