jobs:

  all-tests:
    name: All Tests
    description: |
      This job depends on all unit jobs that need to pass.
      It is depended upon by the super-project(s)!
    priority: 999 # "empty" job = high priority
    depends_on:
      rspec-tests: { job_key: rspec-tests, states: [passed], type: job }
      lint: { job_key: lint, states: [passed], type: job }
    run_when: &DEFAULT_TRIGGERS
      any branch matches:
        type: branch
        include_match: ^.+$
    context:
      task: "echo '✔︎ All dependencies have passed' ; exit 0"

  rspec-tests:
    name: RSpec Tests
    description: Run all specs.
    priority: 1
    run_when: *DEFAULT_TRIGGERS
    context:
      include: cider-ci/context-components/rspec.yml

  lint:
    name: "Linting"
    description: |
      Code checks: static checks and metrics: complexity, duplication, and format,
      also other consistency checks.
    priority: 3
    run_when: *DEFAULT_TRIGGERS
    context:
      task_defaults:
        environment_variables:
          GIT_LINEAR_HISTORY_CHECK_START_SHA: ec23e77651c3b80d4343ead339514512aff946c1
      contexts:
        include:
          - path: cider-ci/context-components/lint/git-lint.yml
          - path: cider-ci/context-components/lint/rspec-lint.yml
          - path: cider-ci/context-components/lint/ruby-lint.yml

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# GITHUB BRANCH PROTECTION                                                        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  good-to-merge:
    name: "⚑ Good To Merge"
    description: |
      This job depends on all jobs that need to pass for "Delivery".
      It is depended upon by GitHub's branch protection (for `master`)!
    priority: 999 # "delivery" job = high priority
    # NOTE: no submodules! no need to run merge-check, also should auto-trigger
    run_when: *DEFAULT_TRIGGERS
    context:
      task: "echo '✔︎ All dependencies have passed and there are no submodules to check' ; exit 0"
    run_when: *DEFAULT_TRIGGERS
    depends_on:
      all-tests: {job_key: all-tests, type: job, states: [passed]}
