pg: &pg
  adapter: postgresql
  host: localhost
  encoding: unicode
  host: localhost
  pool: 5
 
default: &default
  <<: *pg

development: 
  <<: *default
  database: madek_v3_development
  
test: 
  <<: *default
  database: madek_test

personas: 
  <<: *default
  database: madek_personas

production:
  <<: *default
  database: madek_prod


