# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02252ca4ac9b52d6be72f0519e99c27deedfdc22b4217a439663d082b28b16e2f9125ea92a813fd9e1177503a1dc5be9d03b6c3fea441bdaa5ca60439defefeb

test:
  secret_key_base: 6789726116c5e4409386fb42a4a4e077ec2fcaf6b099e902f79612ccf711ed8e2c46847481163703b17645b128579487c9eeb9b2ad03e63db93f2510ff4a1a26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
