jobs:

  code-checks:

    name: Code-Checks

    description: |
      Run static checks and metrics: complexity, duplication, and code format.

    priority: 1

    run_when:
      'any branch matches':
        type: branch
        include_match: ^.+$

    context:

      script_defaults:
        template_environment_variables: true

      task_defaults:

        eager_trials: 1
        max_trials: 2

        git_options:
          submodules:
            include_match: ^.*$
            exclude_match: ^.*vendor\/.*$

        include: cider-ci_v4/task_components/bundle.yml

        environment_variables:
          RAILS_ENV: test
          LANG: "en_US.UTF-8"

      tasks:

        code-complexity:
          name: Code complexity with flog
          scripts:
            test:
              # exclude files which have some Arel
              body: |
                set -eux
                export PATH=~/.rubies/$RUBY/bin:$PATH
                bundle exec cider-ci_flog -m app/ \
                -e app/models/permissions/modules/arel_conditions.rb \
                -e app/models/concerns/media_resources/meta_data_arel_conditions.rb \
                -e app/models/concerns/media_resources/filters/meta_keys.rb

        code-similarity:
          name: Code similarity with flay
          scripts:
            test:
              body: |
                set -eux
                export PATH=~/.rubies/$RUBY/bin:$PATH
                bundle exec cider-ci_flay app/

        lint-ruby:
          name: Lint/Stylecheck with Rubocop
          scripts:
            test:
              body: |
                set -eux
                export PATH=~/.rubies/$RUBY/bin:$PATH
                bundle exec rubocop
